# Generated by Django 4.2.10 on 2024-04-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="cnfValueList",
        ),
    ]
