# Generated by Django 4.2.10 on 2024-04-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0002_remove_cnfmodulevalue_n_attribute"),
        ("general", "0002_delete_cnfvaluelist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="cnfAttribute",
        ),
    ]
