# Generated by Django 4.2.10 on 2024-04-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0003_delete_cnfattribute"),
    ]

    operations = [
        migrations.CreateModel(
            name="cnfAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_attribute_type",
                    models.PositiveSmallIntegerField(verbose_name="Тип атрибута"),
                ),
                (
                    "n_parameter_id",
                    models.PositiveIntegerField(verbose_name="Идентификатор параметра"),
                ),
                (
                    "n_parameter_bit",
                    models.PositiveSmallIntegerField(verbose_name="Бит в параметре"),
                ),
                (
                    "c_name_attribute",
                    models.CharField(max_length=255, verbose_name="Имя атрибута"),
                ),
                (
                    "c_display_attribute",
                    models.CharField(
                        max_length=255, verbose_name="Пользовательское имя"
                    ),
                ),
                (
                    "c_desc_attribute",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "n_attr_min_id",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Минимальное значение id атрибута",
                    ),
                ),
                (
                    "n_attr_max_id",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Максимальное значение id атрибута",
                    ),
                ),
                (
                    "n_attr_min_value",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Минимальное значение атрибута",
                    ),
                ),
                (
                    "n_attr_max_value",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Максимальное значение атрибута",
                    ),
                ),
                (
                    "c_attr_display_group",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Отображаемая группа для атрибута",
                    ),
                ),
                (
                    "n_attr_display_order",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Порядок отображения для атрибута",
                    ),
                ),
                (
                    "n_attribute_sub_type",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Подтип атрибута"
                    ),
                ),
                (
                    "n_parent",
                    models.IntegerField(
                        null=True, verbose_name="Идентификатор родителя"
                    ),
                ),
                (
                    "n_global_object_type",
                    models.PositiveSmallIntegerField(
                        verbose_name="Тип глобального объекта: Модули, Переменные, Оборудование..."
                    ),
                ),
            ],
            options={
                "verbose_name": "Атрибут",
                "verbose_name_plural": "Атрибуты",
            },
        ),
    ]
