# Generated by Django 4.2.10 on 2024-09-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0004_cnfattribute"),
    ]

    operations = [
        migrations.CreateModel(
            name="cnfCommands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_command_index",
                    models.PositiveSmallIntegerField(verbose_name="Индекс команды"),
                ),
                (
                    "с_name",
                    models.CharField(max_length=128, verbose_name="Имя константы"),
                ),
                (
                    "с_desc",
                    models.CharField(
                        max_length=512, verbose_name="Описание команды/запроса/ответа"
                    ),
                ),
            ],
            options={
                "verbose_name": "Команда",
                "verbose_name_plural": "Команды",
            },
        ),
    ]
