# Generated by Django 4.2.10 on 2024-09-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0005_cnfcommands"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cnfcommands",
            old_name="с_desc",
            new_name="c_desc",
        ),
        migrations.RenameField(
            model_name="cnfcommands",
            old_name="с_name",
            new_name="c_name",
        ),
    ]
