# Generated by Django 4.2.11 on 2024-10-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0006_rename_с_desc_cnfcommands_c_desc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="cnfVariableQualityCodes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_code",
                    models.PositiveSmallIntegerField(verbose_name="Код качества"),
                ),
                ("c_name", models.CharField(max_length=64, verbose_name="Имя кода")),
                (
                    "c_desc",
                    models.CharField(max_length=128, verbose_name="Описание кода"),
                ),
            ],
            options={
                "verbose_name": "Код качества",
                "verbose_name_plural": "Коды качества",
            },
        ),
    ]
