# Generated by Django 4.2.11 on 2024-11-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0007_cnfvariablequalitycodes"),
    ]

    operations = [
        migrations.CreateModel(
            name="cnfJournalMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_index",
                    models.PositiveSmallIntegerField(verbose_name="Индекс сообщения"),
                ),
                (
                    "c_obj_index_name",
                    models.CharField(
                        max_length=128, verbose_name="Имя объекта для индекса"
                    ),
                ),
                (
                    "c_desc",
                    models.CharField(
                        max_length=512, verbose_name="Описание команды/запроса/ответа"
                    ),
                ),
                (
                    "c_mes_type",
                    models.CharField(max_length=128, verbose_name="Тип сообщения"),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
