# Generated by Django 4.2.11 on 2024-12-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0008_cnfjournalmessages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfattribute",
            name="n_global_object_type",
            field=models.PositiveSmallIntegerField(
                verbose_name="Тип глобального объекта:\n        Модули, Переменные, Оборудование..."
            ),
        ),
    ]
