# Generated by Django 4.2.11 on 2025-01-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0009_alter_cnfattribute_n_global_object_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="cnfEquipmentAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "c_attr_name",
                    models.CharField(max_length=128, verbose_name="Имя атрибута"),
                ),
                (
                    "c_data_type",
                    models.CharField(max_length=16, verbose_name="Тип данных атрибута"),
                ),
                (
                    "c_reg_type",
                    models.CharField(
                        max_length=128, verbose_name="Наименование типа регистра"
                    ),
                ),
                (
                    "n_offset",
                    models.PositiveSmallIntegerField(
                        verbose_name="Смещение относительно базового адреса"
                    ),
                ),
            ],
            options={
                "verbose_name": "Атрибут оборудования",
                "verbose_name_plural": "Атрибуты оборудования",
            },
        ),
        migrations.CreateModel(
            name="cnfVariableAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "c_attr_name",
                    models.CharField(max_length=128, verbose_name="Имя атрибута"),
                ),
                (
                    "c_data_type",
                    models.CharField(max_length=16, verbose_name="Тип данных атрибута"),
                ),
                (
                    "c_reg_type",
                    models.CharField(
                        max_length=128, verbose_name="Наименование типа регистра"
                    ),
                ),
                (
                    "n_offset",
                    models.PositiveSmallIntegerField(
                        verbose_name="Смещение относительно базового адреса"
                    ),
                ),
            ],
            options={
                "verbose_name": "Атрибут переменной",
                "verbose_name_plural": "Атрибуты переменной",
            },
        ),
    ]
