# Generated by Django 4.2.11 on 2025-03-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0010_cnfequipmentattributes_cnfvariableattributes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfvariablequalitycodes",
            name="c_desc",
            field=models.CharField(max_length=255, verbose_name="Описание кода"),
        ),
    ]
