# Generated by Django 4.2.10 on 2024-04-30 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("general", "0004_cnfattribute"),
    ]

    operations = [
        migrations.CreateModel(
            name="cnfVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                (
                    "n_variable_index",
                    models.IntegerField(verbose_name="Индекс переменной"),
                ),
                (
                    "c_name_variable",
                    models.CharField(max_length=64, verbose_name="Имя переменной"),
                ),
                (
                    "c_desc_variable",
                    models.CharField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Описание переменной",
                    ),
                ),
                (
                    "c_name_section",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Наименование секции",
                    ),
                ),
                (
                    "c_name_position",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Наименование позиции",
                    ),
                ),
                (
                    "c_num_position",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        verbose_name="Номер позиции",
                    ),
                ),
                (
                    "d_last_edit",
                    models.DateTimeField(
                        max_length=256, verbose_name="Дата и время обновления"
                    ),
                ),
                (
                    "c_user_edit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="v_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор изменений",
                    ),
                ),
                (
                    "n_controller",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="v_controllers",
                        to="general.cnfcontroller",
                        verbose_name="Имя контроллера",
                    ),
                ),
            ],
            options={
                "verbose_name": "Переменная",
                "verbose_name_plural": "Переменные",
            },
        ),
        migrations.CreateModel(
            name="cnfVariableDataType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_type_value",
                    models.IntegerField(
                        unique=True, verbose_name="Тип данных переменной - значение"
                    ),
                ),
                (
                    "c_type_name",
                    models.CharField(
                        max_length=32, verbose_name="Имя типа данных переменной"
                    ),
                ),
                (
                    "c_type_desc",
                    models.CharField(
                        max_length=255, verbose_name="Описание типа данных переменной"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип данных переменной",
                "verbose_name_plural": "Типы данных переменных",
            },
        ),
        migrations.CreateModel(
            name="cnfVariableType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_type_value",
                    models.IntegerField(
                        unique=True, verbose_name="Тип переменной - значение"
                    ),
                ),
                (
                    "c_type_name",
                    models.CharField(max_length=32, verbose_name="Тип переменной"),
                ),
                (
                    "c_type_desc",
                    models.CharField(
                        max_length=255, verbose_name="Описание типа переменной"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип переменной",
                "verbose_name_plural": "Типы переменных",
            },
        ),
        migrations.CreateModel(
            name="cnfVariableValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_value", models.FloatField(verbose_name="Значение")),
                (
                    "c_note",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Заметка"
                    ),
                ),
                (
                    "c_formula",
                    models.CharField(blank=True, null=True, verbose_name="Формула"),
                ),
                (
                    "n_attribute",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variable_attributes",
                        to="general.cnfattribute",
                        verbose_name="Attribute ID",
                    ),
                ),
                (
                    "n_variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variable",
                        to="variables.cnfvariable",
                        verbose_name="ID переменной из cnfVariable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение переменной",
                "verbose_name_plural": "Значения переменной",
            },
        ),
        migrations.AddField(
            model_name="cnfvariable",
            name="n_variable_data_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variable_data_types",
                to="variables.cnfvariabledatatype",
                verbose_name="Тип данных переменной",
            ),
        ),
        migrations.AddField(
            model_name="cnfvariable",
            name="n_variable_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variable_types",
                to="variables.cnfvariabletype",
                verbose_name="Тип переменной",
            ),
        ),
    ]
