# Generated by Django 4.2.10 on 2024-05-01 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0003_cnfmodulevalue_n_attribute"),
        ("variables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnfvariable",
            name="n_module_channel",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Канал модуля"
            ),
        ),
        migrations.AddField(
            model_name="cnfvariable",
            name="n_module_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variable_modules",
                to="modules.cnfmodule",
                verbose_name="ID модуля",
            ),
        ),
    ]
