# Generated by Django 4.2.10 on 2024-05-23 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("general", "0004_cnfattribute"),
        ("variables", "0002_cnfvariable_n_module_channel_cnfvariable_n_module_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfvariable",
            name="c_desc_variable",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="cnfvariable",
            name="c_name_variable",
            field=models.CharField(max_length=64, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="cnfvariable",
            name="c_user_edit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Редактор",
            ),
        ),
        migrations.AlterField(
            model_name="cnfvariable",
            name="n_controller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="general.cnfcontroller",
                verbose_name="Контроллер",
            ),
        ),
        migrations.AlterField(
            model_name="cnfvariable",
            name="n_variable_data_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variable_data_types",
                to="variables.cnfvariabledatatype",
                verbose_name="Тип данных",
            ),
        ),
        migrations.AlterField(
            model_name="cnfvariable",
            name="n_variable_index",
            field=models.IntegerField(verbose_name="Индекс"),
        ),
        migrations.AlterField(
            model_name="cnfvariable",
            name="n_variable_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variable_types",
                to="variables.cnfvariabletype",
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="cnfvariablevalue",
            name="n_attribute",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="general.cnfattribute",
                verbose_name="Attribute ID",
            ),
        ),
    ]
