# Generated by Django 4.2.10 on 2024-09-05 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0006_alter_cnfmodule_d_last_edit"),
        ("variables", "0005_alter_cnfvariable_d_last_edit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfvariable",
            name="n_module_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variable_modules",
                to="modules.cnfmodule",
                verbose_name="ID модуля",
            ),
        ),
    ]
