# Generated by Django 4.2.10 on 2024-09-10 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0004_cnfattribute"),
        ("variables", "0006_alter_cnfvariable_n_module_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfvariable",
            name="n_controller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="general.cnfcontroller",
                verbose_name="Контроллер",
            ),
        ),
    ]
