# Generated by Django 4.2.10 on 2024-09-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0007_alter_cnfvariable_n_controller"),
    ]

    operations = [
        migrations.CreateModel(
            name="cnfFormulaSymbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_type",
                    models.SmallIntegerField(unique=True, verbose_name="Тип символа"),
                ),
                (
                    "n_nn_char",
                    models.SmallIntegerField(verbose_name="Идентификатор символа"),
                ),
                ("c_symbol", models.CharField(max_length=2, verbose_name="Символ")),
                ("c_desc", models.CharField(max_length=128, verbose_name="Символ")),
            ],
            options={
                "verbose_name": "Описание символа для формулы переменной",
                "verbose_name_plural": "Описания символов для формулы переменной",
            },
        ),
    ]
