# Generated by Django 4.2.10 on 2024-09-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0008_cnfformulasymbol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfformulasymbol",
            name="c_desc",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Символ"
            ),
        ),
        migrations.AlterField(
            model_name="cnfformulasymbol",
            name="n_nn_char",
            field=models.SmallIntegerField(
                unique=True, verbose_name="Идентификатор символа"
            ),
        ),
    ]
