# Generated by Django 4.2.10 on 2024-09-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0009_alter_cnfformulasymbol_c_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfformulasymbol",
            name="n_nn_char",
            field=models.SmallIntegerField(verbose_name="Идентификатор символа"),
        ),
    ]
