# Generated by Django 4.2.10 on 2024-09-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0010_alter_cnfformulasymbol_n_nn_char"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfformulasymbol",
            name="n_type",
            field=models.SmallIntegerField(verbose_name="Тип символа"),
        ),
    ]
