# Generated by Django 4.2.10 on 2024-09-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0011_alter_cnfformulasymbol_n_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnfformulasymbol",
            name="n_chr",
            field=models.IntegerField(default=0, verbose_name="Идентификатор символа"),
        ),
        migrations.AlterField(
            model_name="cnfformulasymbol",
            name="n_nn_char",
            field=models.SmallIntegerField(
                verbose_name="Идентификатор символа (не используется)"
            ),
        ),
    ]
