# Generated by Django 4.2.10 on 2024-09-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0012_cnfformulasymbol_n_chr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnfvariable",
            name="b_masked",
            field=models.BooleanField(default=False, verbose_name="Замаскирован"),
        ),
    ]
