# Generated by Django 4.2.11 on 2024-12-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0013_cnfvariable_b_masked"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnfvariable",
            name="c_signal_ident",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Идентификатор сигнала",
            ),
        ),
    ]
