# Generated by Django 4.2.11 on 2025-04-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0014_cnfvariable_c_signal_ident"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfformulasymbol",
            name="c_desc",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Символ"
            ),
        ),
    ]
