# Generated by Django 4.2.10 on 2024-04-26 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="cnfModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                ("n_module_index", models.IntegerField(verbose_name="Индекс модуля")),
                (
                    "c_name_module",
                    models.CharField(max_length=64, verbose_name="Имя модуля"),
                ),
                (
                    "c_desc_module",
                    models.CharField(max_length=255, verbose_name="Описание модуля"),
                ),
                (
                    "d_last_edit",
                    models.DateTimeField(
                        max_length=256, verbose_name="Дата и время публикации"
                    ),
                ),
                (
                    "c_user_edit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Редактор",
                    ),
                ),
                (
                    "n_controller",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modules",
                        to="general.cnfcontroller",
                        verbose_name="Контроллер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Модуль",
                "verbose_name_plural": "Модули",
            },
        ),
        migrations.CreateModel(
            name="cnfModuleDataType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_type_value",
                    models.IntegerField(
                        unique=True, verbose_name="Тип данных модуля - значение"
                    ),
                ),
                (
                    "c_type_name",
                    models.CharField(
                        max_length=32, verbose_name="Имя типа данных модуля"
                    ),
                ),
                (
                    "c_type_desc",
                    models.CharField(
                        max_length=255, verbose_name="Описание типа данных модуля"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип данных модуля",
                "verbose_name_plural": "Типы данных модулей",
            },
        ),
        migrations.CreateModel(
            name="cnfModuleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_type_value",
                    models.IntegerField(
                        unique=True, verbose_name="Тип модуля - значение"
                    ),
                ),
                (
                    "c_type_name",
                    models.CharField(max_length=32, verbose_name="Тип модуля"),
                ),
                (
                    "c_type_desc",
                    models.CharField(
                        max_length=255, verbose_name="Описание типа модуля"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип модуля",
                "verbose_name_plural": "Типы модулей",
            },
        ),
        migrations.CreateModel(
            name="cnfModuleValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_value", models.FloatField(verbose_name="Module value")),
                (
                    "c_note",
                    models.CharField(max_length=255, verbose_name="Module value note"),
                ),
                (
                    "n_attribute",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="general.cnfattribute",
                        verbose_name="Attribute ID",
                    ),
                ),
                (
                    "n_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attr_values",
                        to="modules.cnfmodule",
                        verbose_name="Module ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение модуля",
                "verbose_name_plural": "Значения модуля",
            },
        ),
    ]
