# Generated by Django 4.2.10 on 2024-04-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cnfmodulevalue",
            name="n_attribute",
        ),
    ]
