# Generated by Django 4.2.10 on 2024-04-26 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0004_cnfattribute"),
        ("modules", "0002_remove_cnfmodulevalue_n_attribute"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnfmodulevalue",
            name="n_attribute",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="general.cnfattribute",
                verbose_name="Attribute ID",
            ),
        ),
    ]
