# Generated by Django 4.2.10 on 2024-05-23 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("general", "0004_cnfattribute"),
        ("modules", "0003_cnfmodulevalue_n_attribute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfmodule",
            name="c_user_edit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Редактор",
            ),
        ),
        migrations.AlterField(
            model_name="cnfmodule",
            name="d_last_edit",
            field=models.DateTimeField(
                max_length=256, verbose_name="Дата и время обновления"
            ),
        ),
        migrations.AlterField(
            model_name="cnfmodule",
            name="n_controller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="general.cnfcontroller",
                verbose_name="Контроллер",
            ),
        ),
        migrations.AlterField(
            model_name="cnfmodulevalue",
            name="c_note",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Заметка"
            ),
        ),
        migrations.AlterField(
            model_name="cnfmodulevalue",
            name="f_value",
            field=models.FloatField(verbose_name="Значение"),
        ),
        migrations.AlterField(
            model_name="cnfmodulevalue",
            name="n_attribute",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="general.cnfattribute",
                verbose_name="Attribute ID",
            ),
        ),
    ]
