# Generated by Django 4.2.10 on 2024-09-05 04:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0005_alter_cnfmodule_d_last_edit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfmodule",
            name="d_last_edit",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                max_length=256,
                verbose_name="Дата и время обновления",
            ),
        ),
    ]
