# Generated by Django 4.2.10 on 2024-05-23 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("general", "0004_cnfattribute"),
    ]

    operations = [
        migrations.CreateModel(
            name="cnfEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                (
                    "d_last_edit",
                    models.DateTimeField(
                        max_length=256, verbose_name="Дата и время обновления"
                    ),
                ),
                ("n_equipment_index", models.IntegerField(verbose_name="Индекс")),
                (
                    "c_name_equipment",
                    models.CharField(max_length=64, verbose_name="Имя"),
                ),
                (
                    "c_desc_equipment",
                    models.CharField(
                        blank=True, max_length=2000, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "c_name_section",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Наименование секции",
                    ),
                ),
                (
                    "c_name_position",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Наименование позиции",
                    ),
                ),
                (
                    "c_num_position",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        verbose_name="Номер позиции",
                    ),
                ),
                (
                    "c_user_edit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Редактор",
                    ),
                ),
                (
                    "n_controller",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="general.cnfcontroller",
                        verbose_name="Контроллер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Переменная",
                "verbose_name_plural": "Переменные",
            },
        ),
        migrations.CreateModel(
            name="cnfEquipmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_type_value",
                    models.IntegerField(
                        unique=True, verbose_name="Тип оборудования - значение"
                    ),
                ),
                (
                    "c_type_name",
                    models.CharField(max_length=32, verbose_name="Тип оборудования"),
                ),
                (
                    "c_type_desc",
                    models.CharField(
                        max_length=255, verbose_name="Описание типа оборудования"
                    ),
                ),
                (
                    "n_global_object_type",
                    models.PositiveSmallIntegerField(
                        verbose_name="Тип глобального объекта: Модули, Переменные, Оборудование..."
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип оборудования",
                "verbose_name_plural": "Типы оборудования",
            },
        ),
        migrations.CreateModel(
            name="cnfEquipmentValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_value", models.FloatField(verbose_name="Значение")),
                (
                    "c_note",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Заметка"
                    ),
                ),
                (
                    "n_attribute",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="general.cnfattribute",
                        verbose_name="Attribute ID",
                    ),
                ),
                (
                    "n_equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="equipments.cnfequipment",
                        verbose_name="ID оборудования из cnfEquipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение переменной",
                "verbose_name_plural": "Значения переменной",
            },
        ),
        migrations.AddField(
            model_name="cnfequipment",
            name="n_type_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment",
                to="equipments.cnfequipmenttype",
                verbose_name="Тип оборудования",
            ),
        ),
    ]
