# Generated by Django 4.2.10 on 2024-05-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="cnfEquipmentRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_role_index",
                    models.IntegerField(
                        unique=True, verbose_name="Индекс роли оборудования"
                    ),
                ),
                (
                    "c_role_desc",
                    models.CharField(
                        max_length=32, verbose_name="Описание роли оборудования"
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль оборудования",
                "verbose_name_plural": "Роли оборудования",
            },
        ),
        migrations.CreateModel(
            name="cnfEquipmentVariableRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_role_index",
                    models.IntegerField(
                        unique=True, verbose_name="Индекс роли переменной"
                    ),
                ),
                (
                    "c_role_desc",
                    models.CharField(
                        max_length=32, verbose_name="Описание роли переменной"
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль переменной",
                "verbose_name_plural": "Роли переменной",
            },
        ),
    ]
