# Generated by Django 4.2.10 on 2024-05-23 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0003_alter_cnfvariable_c_desc_variable_and_more"),
        ("equipments", "0002_cnfequipmentrole_cnfequipmentvariablerole"),
    ]

    operations = [
        migrations.CreateModel(
            name="cnfEquipmentLinkedVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n_timer", models.IntegerField(default=0, verbose_name="Таймер")),
                (
                    "n_equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_variable",
                        to="equipments.cnfequipment",
                        verbose_name="ID оборудования из cnfEquipment",
                    ),
                ),
                (
                    "n_role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_variable",
                        to="equipments.cnfequipmentvariablerole",
                        verbose_name="Роль переменной",
                    ),
                ),
                (
                    "n_variable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_variable",
                        to="variables.cnfvariable",
                        verbose_name="Ссылка на переменную",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка на переменную",
                "verbose_name_plural": "Ссылки на переменные",
            },
        ),
    ]
