# Generated by Django 4.2.10 on 2024-05-23 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0003_cnfequipmentlinkedvariable"),
    ]

    operations = [
        migrations.CreateModel(
            name="cnfEquipmentLinkedEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n_timer", models.IntegerField(default=0, verbose_name="Таймер")),
                (
                    "n_equipment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_equipment",
                        to="equipments.cnfequipment",
                        verbose_name="Ссылка на оборудование",
                    ),
                ),
                (
                    "n_role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_equipment",
                        to="equipments.cnfequipmentrole",
                        verbose_name="Роль оборудования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка на оборудование",
                "verbose_name_plural": "Ссылки на оборудование",
            },
        ),
    ]
