# Generated by Django 4.2.10 on 2024-05-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0004_cnfequipmentlinkedequipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnfequipmentrole",
            name="c_role_name",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Имя флага роли оборудования",
            ),
        ),
        migrations.AddField(
            model_name="cnfequipmentvariablerole",
            name="c_role_name",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Имя флага роли переменной",
            ),
        ),
    ]
