# Generated by Django 4.2.10 on 2024-05-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0005_cnfequipmentrole_c_role_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cnfequipmentvariablerole",
            options={
                "verbose_name": "Роль переменной",
                "verbose_name_plural": "Роли переменных",
            },
        ),
        migrations.AlterField(
            model_name="cnfequipmentrole",
            name="c_role_desc",
            field=models.CharField(
                max_length=512, verbose_name="Описание роли оборудования"
            ),
        ),
        migrations.AlterField(
            model_name="cnfequipmentrole",
            name="c_role_name",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Имя флага роли оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="cnfequipmentvariablerole",
            name="c_role_desc",
            field=models.CharField(
                max_length=512, verbose_name="Описание роли переменной"
            ),
        ),
        migrations.AlterField(
            model_name="cnfequipmentvariablerole",
            name="c_role_name",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Имя флага роли переменной",
            ),
        ),
    ]
