# Generated by Django 4.2.10 on 2024-05-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0006_alter_cnfequipmentvariablerole_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfequipmentrole",
            name="c_role_name",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Имя флага роли оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="cnfequipmentvariablerole",
            name="c_role_name",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Имя флага роли переменной",
            ),
        ),
    ]
