# Generated by Django 4.2.10 on 2024-05-29 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0007_alter_cnfequipmentrole_c_role_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnfequipmentlinkedequipment",
            name="n_equipment_link",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_equipment_link",
                to="equipments.cnfequipment",
                verbose_name="Ссылка на оборудование",
            ),
        ),
        migrations.AlterField(
            model_name="cnfequipmentlinkedequipment",
            name="n_equipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_equipment",
                to="equipments.cnfequipment",
                verbose_name="ID оборудования из cnfEquipment",
            ),
        ),
    ]
