# Generated by Django 4.2.10 on 2024-05-29 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0003_alter_cnfvariable_c_desc_variable_and_more"),
        ("equipments", "0008_cnfequipmentlinkedequipment_n_equipment_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="cnfEquipmentLinkedWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n_bit", models.SmallIntegerField(verbose_name="Номер бита")),
                ("n_word_type", models.SmallIntegerField(verbose_name="Тип слова")),
                (
                    "n_equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_word",
                        to="equipments.cnfequipment",
                        verbose_name="ID оборудования из cnfEquipment",
                    ),
                ),
                (
                    "n_role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_word",
                        to="equipments.cnfequipmentvariablerole",
                        verbose_name="Роль переменной",
                    ),
                ),
                (
                    "n_variable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_word",
                        to="variables.cnfvariable",
                        verbose_name="Ссылка на переменную",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка на слово",
                "verbose_name_plural": "Ссылки на слова",
            },
        ),
    ]
