# Generated by Django 4.2.10 on 2024-06-10 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0003_alter_cnfvariable_c_desc_variable_and_more"),
        ("equipments", "0009_cnfequipmentlinkedword"),
    ]

    operations = [
        migrations.CreateModel(
            name="cnfEquipmentPIDVariableRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_role_index",
                    models.IntegerField(
                        unique=True, verbose_name="Индекс роли переменной ПИД"
                    ),
                ),
                (
                    "c_role_name",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Имя флага роли переменной ПИД",
                    ),
                ),
                (
                    "c_role_desc",
                    models.CharField(
                        max_length=512, verbose_name="Описание роли переменной ПИД"
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль ПИД",
                "verbose_name_plural": "Роли ПИД",
            },
        ),
        migrations.CreateModel(
            name="cnfEquipmentLinkedPIDVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n_timer", models.IntegerField(default=0, verbose_name="Таймер")),
                (
                    "n_equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_pid_variable",
                        to="equipments.cnfequipment",
                        verbose_name="ID оборудования из cnfEquipment",
                    ),
                ),
                (
                    "n_role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_pid_variable",
                        to="equipments.cnfequipmentpidvariablerole",
                        verbose_name="Роль переменной ПИД",
                    ),
                ),
                (
                    "n_variable_link",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_pid_variable_link",
                        to="variables.cnfvariable",
                        verbose_name="Ссылка на переменную",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка на переменную ПИД",
                "verbose_name_plural": "Ссылки на переменные ПИД",
            },
        ),
    ]
