# Generated by Django 4.2.10 on 2024-08-06 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0010_cnfequipmentpidvariablerole_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="cnfSequenceRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_role_index",
                    models.IntegerField(
                        unique=True, verbose_name="Индекс роли переменной"
                    ),
                ),
                (
                    "b_role_equipment",
                    models.BooleanField(
                        null=True, verbose_name="Роль для оборудования"
                    ),
                ),
                (
                    "c_role_name",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Имя флага роли переменной",
                    ),
                ),
                (
                    "c_role_desc",
                    models.CharField(
                        max_length=512, verbose_name="Описание роли переменной"
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль переменной",
                "verbose_name_plural": "Роли переменных",
            },
        ),
        migrations.AlterModelOptions(
            name="cnfequipmentpidvariablerole",
            options={
                "verbose_name": "Роль переменной ПИД",
                "verbose_name_plural": "Роли переменных ПИД",
            },
        ),
        migrations.CreateModel(
            name="cnfSequenceLinkedVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n_timer", models.IntegerField(null=True, verbose_name="Таймер")),
                ("n_step", models.IntegerField(null=True, verbose_name="Таймер")),
                (
                    "n_equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seq_linked_variable",
                        to="equipments.cnfequipment",
                        verbose_name="ID оборудования из cnfEquipment",
                    ),
                ),
                (
                    "n_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seq_linked_variable",
                        to="equipments.cnfsequencerole",
                        verbose_name="Роль оборудования",
                    ),
                ),
                (
                    "n_variable_link",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seq_linked_variable_link",
                        to="equipments.cnfequipment",
                        verbose_name="Ссылка на переменную",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка на переменную (последовательности)",
                "verbose_name_plural": "Ссылки на переменные (последовательности)",
            },
        ),
        migrations.CreateModel(
            name="cnfSequenceLinkedEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n_timer", models.IntegerField(null=True, verbose_name="Таймер")),
                ("n_step", models.IntegerField(null=True, verbose_name="Таймер")),
                (
                    "n_equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seq_linked_equipment",
                        to="equipments.cnfequipment",
                        verbose_name="ID оборудования из cnfEquipment",
                    ),
                ),
                (
                    "n_equipment_link",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seq_linked_equipment_link",
                        to="equipments.cnfequipment",
                        verbose_name="Ссылка на оборудование",
                    ),
                ),
                (
                    "n_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seq_linked_equipment",
                        to="equipments.cnfsequencerole",
                        verbose_name="Роль оборудования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка на оборудование (последовательности)",
                "verbose_name_plural": "Ссылки на оборудование (последовательности)",
            },
        ),
    ]
