# Generated by Django 4.2.10 on 2024-08-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0011_cnfsequencerole_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnfsequencelinkedequipment",
            name="n_seq_type",
            field=models.SmallIntegerField(
                null=True,
                verbose_name="Тип последовательности: запуск, б.запуск, останов, авар.останов",
            ),
        ),
    ]
