# Generated by Django 4.2.10 on 2024-08-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0012_cnfsequencelinkedequipment_n_seq_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfsequencelinkedequipment",
            name="n_seq_type",
            field=models.SmallIntegerField(
                verbose_name="Тип последовательности: запуск, б.запуск, останов, авар.останов"
            ),
        ),
    ]
