# Generated by Django 4.2.10 on 2024-08-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0013_alter_cnfsequencelinkedequipment_n_seq_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnfsequencelinkedvariable",
            name="n_seq_type",
            field=models.SmallIntegerField(
                default=1,
                verbose_name="Тип последовательности: запуск, б.запуск, останов, авар.останов",
            ),
            preserve_default=False,
        ),
    ]
