# Generated by Django 4.2.10 on 2024-08-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0014_cnfsequencelinkedvariable_n_seq_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfsequencelinkedequipment",
            name="n_step",
            field=models.IntegerField(verbose_name="Таймер"),
        ),
        migrations.AlterField(
            model_name="cnfsequencelinkedvariable",
            name="n_step",
            field=models.IntegerField(verbose_name="Таймер"),
        ),
    ]
