# Generated by Django 4.2.10 on 2024-08-13 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0003_alter_cnfvariable_c_desc_variable_and_more"),
        ("equipments", "0015_alter_cnfsequencelinkedequipment_n_step_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfsequencelinkedequipment",
            name="n_seq_type",
            field=models.SmallIntegerField(
                verbose_name="Тип последовательности: 1 -запуск, 2 - б.запуск, 3 - останов, 4 - авар.останов"
            ),
        ),
        migrations.AlterField(
            model_name="cnfsequencelinkedvariable",
            name="n_seq_type",
            field=models.SmallIntegerField(
                verbose_name="Тип последовательности: 1 -запуск, 2 - б.запуск, 3 - останов, 4 - авар.останов"
            ),
        ),
        migrations.AlterField(
            model_name="cnfsequencelinkedvariable",
            name="n_variable_link",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seq_linked_variable_link",
                to="variables.cnfvariable",
                verbose_name="Ссылка на переменную",
            ),
        ),
    ]
