# Generated by Django 4.2.10 on 2024-09-05 04:20

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0016_alter_cnfsequencelinkedequipment_n_seq_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfequipment",
            name="d_last_edit",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 5, 4, 20, 28, 270887, tzinfo=datetime.timezone.utc
                ),
                max_length=256,
                verbose_name="Дата и время обновления",
            ),
        ),
    ]
