# Generated by Django 4.2.10 on 2024-09-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0019_alter_cnfequipment_n_controller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfequipmentlinkedvariable",
            name="n_timer",
            field=models.FloatField(default=0, verbose_name="Таймер"),
        ),
    ]
