# Generated by Django 4.2.10 on 2024-09-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0020_alter_cnfequipmentlinkedvariable_n_timer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfequipmentlinkedequipment",
            name="n_timer",
            field=models.FloatField(default=0, verbose_name="Таймер"),
        ),
        migrations.AlterField(
            model_name="cnfequipmentlinkedpidvariable",
            name="n_timer",
            field=models.FloatField(default=0, verbose_name="Таймер"),
        ),
        migrations.AlterField(
            model_name="cnfsequencelinkedequipment",
            name="n_timer",
            field=models.FloatField(null=True, verbose_name="Таймер"),
        ),
    ]
