# Generated by Django 4.2.10 on 2024-09-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0021_alter_cnfequipmentlinkedequipment_n_timer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnfequipment",
            name="b_masked",
            field=models.BooleanField(default=False, verbose_name="Замаскирован"),
        ),
    ]
