# Generated by Django 4.2.10 on 2024-09-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0022_cnfequipment_b_masked"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnfsequencelinkedequipment",
            name="b_masked",
            field=models.BooleanField(default=False, verbose_name="Замаскирован"),
        ),
        migrations.AddField(
            model_name="cnfsequencelinkedvariable",
            name="b_masked",
            field=models.BooleanField(default=False, verbose_name="Замаскирован"),
        ),
    ]
