# Generated by Django 4.2.10 on 2024-09-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0023_cnfsequencelinkedequipment_b_masked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnfequipmentlinkedequipment",
            name="b_masked",
            field=models.BooleanField(default=False, verbose_name="Замаскирован"),
        ),
        migrations.AddField(
            model_name="cnfequipmentlinkedpidvariable",
            name="b_masked",
            field=models.BooleanField(default=False, verbose_name="Замаскирован"),
        ),
        migrations.AddField(
            model_name="cnfequipmentlinkedvariable",
            name="b_masked",
            field=models.BooleanField(default=False, verbose_name="Замаскирован"),
        ),
    ]
