# Generated by Django 4.2.10 on 2024-09-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0024_cnfequipmentlinkedequipment_b_masked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfsequencelinkedvariable",
            name="n_timer",
            field=models.FloatField(null=True, verbose_name="Таймер"),
        ),
    ]
