# Generated by Django 4.2.11 on 2025-03-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0025_alter_cnfsequencelinkedvariable_n_timer"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnfequipmentlinkedequipment",
            name="n_index",
            field=models.IntegerField(default=1, verbose_name="Индекс"),
        ),
        migrations.AddField(
            model_name="cnfequipmentlinkedpidvariable",
            name="n_index",
            field=models.IntegerField(default=1, verbose_name="Индекс"),
        ),
        migrations.AddField(
            model_name="cnfequipmentlinkedvariable",
            name="n_index",
            field=models.IntegerField(default=1, verbose_name="Индекс"),
        ),
    ]
