# Generated by Django 4.2.11 on 2025-03-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0026_cnfequipmentlinkedequipment_n_index_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfequipmentlinkedequipment",
            name="n_index",
            field=models.IntegerField(null=True, verbose_name="Индекс"),
        ),
        migrations.AlterField(
            model_name="cnfequipmentlinkedpidvariable",
            name="n_index",
            field=models.IntegerField(null=True, verbose_name="Индекс"),
        ),
        migrations.AlterField(
            model_name="cnfequipmentlinkedvariable",
            name="n_index",
            field=models.IntegerField(null=True, verbose_name="Индекс"),
        ),
    ]
