# Generated by Django 4.2.11 on 2025-03-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0027_alter_cnfequipmentlinkedequipment_n_index_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnfequipmentrole",
            name="c_group",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Описание группы оборудования",
            ),
        ),
        migrations.AddField(
            model_name="cnfequipmentrole",
            name="n_priority",
            field=models.SmallIntegerField(
                blank=True,
                default=10,
                null=True,
                verbose_name="Приоритет роли оборудования",
            ),
        ),
    ]
