# Generated by Django 4.2.11 on 2025-03-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0028_cnfequipmentrole_c_group_cnfequipmentrole_n_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnfequipmentvariablerole",
            name="c_group",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Описание группы переменной",
            ),
        ),
        migrations.AddField(
            model_name="cnfequipmentvariablerole",
            name="n_priority",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Приоритет роли переменной"
            ),
        ),
        migrations.AlterField(
            model_name="cnfequipmentrole",
            name="n_priority",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Приоритет роли оборудования"
            ),
        ),
    ]
