# Generated by Django 4.2.11 on 2025-03-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0029_cnfequipmentvariablerole_c_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfequipmentrole",
            name="c_group",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Описание группы оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="cnfequipmentvariablerole",
            name="c_group",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Описание группы переменной",
            ),
        ),
    ]
