# Generated by Django 4.2.11 on 2025-03-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0030_alter_cnfequipmentrole_c_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfequipment",
            name="c_num_position",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Номер позиции"
            ),
        ),
    ]
