# Generated by Django 4.2.10 on 2025-05-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0031_alter_cnfequipment_c_num_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnfequipmentrole",
            name="c_role_oper_desc",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="Описание роли переменной для оператора",
            ),
        ),
        migrations.AddField(
            model_name="cnfequipmentvariablerole",
            name="c_role_oper_desc",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="Описание роли переменной для оператора",
            ),
        ),
    ]
