# Generated by Django 4.2.10 on 2025-10-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0032_cnfequipmentrole_c_role_oper_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnfequipmentrole",
            name="c_role_oper_desc",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="Описание роли оборуования для оператора",
            ),
        ),
    ]
